Ecommerce/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ecom import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='ecom/login.html'), name='login'),
    path('product/<int:pk>/', views.item_details, name='item-detail'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-single-from-cart/<int:pk>/', views.remove_single_from_cart, name='remove-single-from-cart'),
    path('cart-summary', views.cart_summary, name='cart-summary'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from PIL import Image


# Models/tables create

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    description = models.TextField()
    image = models.ImageField(default='shirt.jpeg', upload_to='products')

    def __str__(self):
        return self.title

    # NB: Canonical url: returns the url as a string..to the browser
    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={'pk': self.pk})

    def get_remove_from_cart_url(self):
        return reverse('remove-from-cart', kwargs={'pk': self.pk})




# otherwise knows as the Cart table
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()




class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

ecom/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Order, OrderItem, Item

# Create your views here.

def home(request):
    template_name = 'ecom/home.html'
    order = Order.objects.get(user=request.user, ordered=False)
    items = Item.objects.all().order_by("-title")
    paginator = Paginator(items, 4)
    page = request.GET.get('page')
    try:
        pagelist = paginator.page(page)
    except PageNotAnInteger:
        pagelist = paginator.page(1)
    except EmptyPage:
        pagelist = paginator.page(paginator.num_pages)
    context = {'items': pagelist, 'Order_Summary': order}
    return render(request, template_name, context)

def item_details(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order = Order.objects.get(user=request.user, ordered=False)
    template_name = 'ecom/item_details.html',
    context = {'item': item, 'Order_Summary': order}
    return render(request, template_name, context)

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    # Get the present user...
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        # if the instance exists....grab the user
        order = order_qs[0]
        #  T0 check if the order_item is in the OrderCharter
        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f'This item {order_item.item.title} quantity is updated')
            return redirect('cart-summary')
        else:
            order.items.add(order_item)
            messages.success(request, f'This item has been added to your Shopping Cart')
            return redirect('cart-summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.success(request, f'This item has been added to your Shopping Cart')
        return redirect('cart-summary')



@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]  # grab user instance of the order
        # the check if the order item is in the order..
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            # first remove from order... then completely deletes it..
            order.items.remove(order_item)
            order_item.delete()
            messages.warning(request, f'Item {item.title} is removed')
            return redirect('cart-summary')
        else:
            messages.warning(request, f'Invalid request, item is not present in your cart')
            return redirect('/')
    else:
        messages.warning(request, f'Sorry You do not posses an active order')
        return redirect('/')



@login_required
def remove_single_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]  # grab the instance of the order
        # check if the order is in the shopping cart
        if order.items.filter(item__pk=item.pk).exists():
            # then grap the particular ordered_item instance
            order_item = OrderItem.objects.filter(user=request.user, item=item, ordered=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f'This item {item.title} quantity is updated')
            else:
                order.items.remove(order_item)
                order_item.delete()
                messages.warning(request, f'This item {item.title} is removed from your cart')
            return redirect('cart-summary')
        else:
            messages.warning(request, f'This item does not exist in your cart! Add now')
            return render(request, 'ecom/item_details.html')
    else:
        messages.warning(request, f'You not have an active order ')
        return redirect('/')


@login_required
def cart_summary(request):
    template_name = 'ecom/cart_summary.html'
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        context = {'Order_Summary': order}
        return render(request, template_name, context)
    except ObjectDoesNotExist:
        messages.warning(request, f'Sorry You do not have an active Order')
        return redirect("cart_summary")



def checkout_view(request):
    pass

ecom/templates/ecom/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=0">
	<link rel="stylesheet"  type="text/css" href="{% static 'ecom/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ecom/css/main.css' %}">
    <title>{% block title %}Ecommerce System{% endblock %}</title>
</head>
   <body>
      {% include 'ecom/navigation.html' %}
      <!--start of jumbotron -->
      <div class="jumbotron jumbotron-fluid bg-secondary mt-5">
          <div class="container text-center text-white" style="font-family: 'Trebuchet MS';">
              <h1 class="text-uppercase">favorite store</h1>
                <h2>Welcome to Our Ecommerce Smart Store</h2>
                    <h3>Checkout Our Awesome Products</h3>
                        <p><i>Explore our collections</i></p>
                   <a href="#" type="submit" class="btn btn-info">Create Account</a>
                  <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
          </div>
      </div>
      <!----End of jumbotron-->
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                  <!--Start of inner navbar-->
                  <nav class="navbar navbar-expand-md bg-dark text-white">
                      <a class="navbar-brand">Categories: </a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse"
                              data-target="#insideNav">
                          <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse justify-content" id="insideNav">
                          <ul class="navbar-nav text-white">
                              <li class="navbar-item"><a class="nav-link active" href="#">Shirts</a></li>
                              <li><a class="nav-link" href="#">Trousers</a></li>
                              <li><a class="nav-link" href="#">Spotwears</a></li>
                          </ul>
                      </div>
                      <form class="form-inline">
                          <input class="form-control mr-sm-2" type="search"
                                 placeholder="search" aria-label="Search">
                          <button class="btn btn-sm btn-primary my-2 my-sm-0"
                                  type="submit">filter-By</button>
                      </form>
                  </nav><!--End of inner navbar-->
              </div>
          </div>
      </div>
      <div class="container mt-3 pt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
      </div>
      {% block content %}
          <!----There goes the contents of individual pages-->
      {% endblock %}

      <footer class="footer bg-secondary" style="color: #cbd5db; margin-top: 200px; padding: 30px">
        <div class="container">
            <!--icons to be added later for more UX/UI-->
             <p class="text-center">&copy; copyright 2020; All rights reserved..Powered by HorlaCode Team<br>
             We are at your service <i>07037347461</i><br>
             Email us: olasunkanmiadu33@gmail.com</p>
        </div>
      </footer>
      <script src="{% static 'ecom/js/jquery.min.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.bundle.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'ecom/js/fontawesome-all.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.min.js' %}"></script>
   </body>
</html>

ecom/templates/ecom/base_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=0">
	<link rel="stylesheet"  type="text/css" href="{% static 'ecom/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ecom/css/main.css' %}">
    <title>{% block title %}Product {{ item.title }}{% endblock %}</title>
</head>
   <body>
      {%  include 'ecom/navigation.html' %}
      <!---Alert for dismissible messages-->
      <div class="container mt-4 pt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
      </div>
      {% block content %}
          <!----There goes the contents of individual pages-->
      {% endblock %}

      <footer class="footer bg-secondary" style="color: #cbd5db; margin-top: 200px; padding: 30px">
        <div class="container">
            <!--icons to be added later for more UX/UI-->
             <p class="text-center">&copy; copyright 2020; All rights reserved..Powered by HorlaCode Team<br>
             We are at your service <i>07037347461</i><br>
             Email us: olasunkanmiadu33@gmail.com</p>
        </div>
      </footer>
      <script src="{% static 'ecom/js/jquery.min.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.bundle.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'ecom/js/fontawesome-all.js' %}"></script>
      <script src="{% static 'ecom/js/bootstrap.min.js' %}"></script>
   </body>
</html>

ecom/templates/ecom/cart_summary.html
{% extends 'ecom/base_detail.html' %}
{% load humanize %}
<title>{% block title %}Cart-Summary{% endblock %}</title>

{% block content %}
    <div class="container">
        <h1 class="text-black text-center pt-3 mt-3"><b>Cart-Index</b></h1>
        <div class="js_form_body">
            <table class="table" id="js_book_table">
                <thead>
                  <tr>
                    <th>S/N</th>
                    <th>Item Title</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total Item Price</th>
                  </tr>
                </thead>
                <tbody>
                      {% for order_item in Order_Summary.items.all %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ order_item.item.title }}</td>
                          <td>{% if order_item.item.discount_price %}
                              &#8358;{{ order_item.item.discount_price }}
                              {% else %}
                              &#8358;{{ order_item.item.price }}
                              {% endif %}
                          </td>
                          <td>
                            <a href="{% url 'remove-single-from-cart' order_item.item.pk %}">
                                <i class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'add-to-cart' order_item.item.pk %}">
                                <i class="fas fa-plus ml-2"></i></a>
                          </td>
                          <!---The Total Price Data function called from the DB-->
                            <td>
                                {% if order_item.item.discount_price %}
                                    &#8358;{{ order_item.get_total_discount_item_price|intcomma }}
                                    <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                                {% else %}
                                    &#8358;{{ order_item.get_total_item_price|intcomma }}
                                {% endif %}
                                <a style='color: red;' href="{{ order_item.item.get_remove_from_cart_url }}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                      {% empty %}
                        <tr>
                          <td colspan="7" class="text-center bg-warning">Empty Cart</td>
                        </tr>
                        <tr>
                          <td colspan="5"><a class='btn btn-primary float-right' href='/'>Continue shopping</a></td>
                        </tr>
                      {% endfor %}
                      {% if Order_Summary.get_total %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td><b>&#8358;{{ Order_Summary.get_total }}</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='#'>Proceed to checkout</a>
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                            </td>
                        </tr>
                      {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

ecom/templates/ecom/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=0">
	<link rel="stylesheet"  type="text/css" href="{% static 'ecom/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ecom/css/main.css' %}">
{#    <style>#}
{#        body{#}
{#            background-image: url("{% static 'ecom/img/back.jpg' %}");#}
{#            height: 100%;#}
{#            background-position: center;#}
{#            background-repeat: no-repeat;#}
{#            background-size: cover;#}
{#        }#}
{#    </style>#}
</head>

ecom/templates/ecom/home.html
{% extends 'ecom/base.html' %}
{% load humanize %}

{% block content %}
   <!---Display Contents from the database-->
    <div class="container">
        <div class="row">
            {% for item in items %}
                <div class="col-sm-3">
                    <div class="card shadow-lg mb-2" style="width: 17.5rem;">
                        {% if item.image is not None %}
                            <img src="{{ item.image.url }}"
                                 style="height: 300px;" class="card-img-top" alt="Item-image">
                        {% endif %}
                        <div class="card-body text-center">
                            <div class="card-title"><b>
                                <a href="{% url 'item-detail' item.pk %}">{{ item.title }}</a></b></div>
                            {% if item.discount_price %}
                                <h3><del>&#8358;{{ item.price }}</del>  &#8358;{{ item.discount_price }}</h3>
                            {% else %}
                                <h3>&#8358;{{ item.price|intcomma }}</h3>
                            {% endif %}
                            <span class="badge badge-{{ item.get_label_display }} p-1">New item</span>
                            <a class="btn btn-info btn-sm" type="submit"
                              href="{{ item.get_add_to_cart_url }}">
                               <i class="fas fa-shopping-cart fa-1x"></i> Add-to-Cart</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!----Pagination to manage products --pages-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12 mt-1" style="margin-left: 30rem;">
                    {% if items.has_other_pages %}
                        {% if items.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ items.previous_page_number }}">Previous</a>
                        {% endif %}
                        {% for num in items.paginator.page_range %}
                            {% if items.number == num %}
                              <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                            {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
                              <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}
                        {% if items.has_next %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ items.next_page_number }}">Next</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ items.paginator.num_pages }}">Last</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ecom/templates/ecom/item_details.html
{% extends 'ecom/base_detail.html' %}
<title>{% block title %}Product {{ item.title }}{% endblock %}</title>
{% load humanize %}
{%  block content %}
        <!--A detail for page for each products separately-->
        <div class="container mt-5 pt-5">
           <div class="row">
               <div class="col-sm-4">
                    <div class="card shadow-lg mb-2" style="width: 17.5rem;">
                        {% if item.image is not None %}
                            <img src="{{ item.image.url }}"
                                 style="height: 300px;" class="card-img-top" alt="Item-image">
                        {% endif %}
                        <div class="card-body text-center">
                            <div class="card-title"><b>
                                <a href="{% url 'item-detail' item.pk %}">{{ item.title }}</a></b></div>
                            <span class="badge badge-{{ item.get_label_display }} p-2">{{ item.get_category_display }}</span>
                        </div>
                    </div>
               </div>
               <div class="col-sm-6">
                   <div class="item-section">
                       <h3 class="#">{{ item.title }}</h3>
                       {% if item.discount_price %}
                           <h3><del>&#8358;{{ item.price }}</del> &#8358;{{ item.discount_price }}</h3>
                       {% else %}
                           <h3>&#8358;{{ item.price|intcomma }}</h3>
                       {% endif %}
                       <div class="card">
                           <div class="card-header"><b>Product Description</b></div>
                           <div class="card-body">
                               {{ item.description }}
                           </div>
                       </div>
                       <div class="cart-button mt-3">
                           <a class="btn btn-info btn-sm" type="submit"
                              href="{% url 'add-to-cart' item.pk %}">
                               <i class="fas fa-shopping-cart"></i> Add-to-Cart</a>
                           <a class="btn btn-danger btn-sm" type="submit"
                              href="{% url 'remove-from-cart' item.pk %}">
                               <i class="fas fa-trash"></i> Remove-from-Cart</a>
                       </div>

                   </div>
               </div>
           </div>
        </div>

{% endblock %}

ecom/templates/ecom/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=0">
	<link rel="stylesheet"  type="text/css" href="{% static 'ecom/css/bootstrap.min.css' %}">
    <title>{% block title %}Ecommerce Login{% endblock %}</title>
    <style>
{#        body{#}
{#            background-image: url("{% static 'ecom/img/back.jpg' %}");#}
{#            height: 100%;#}
{#            background-position: center;#}
{#            background-repeat: no-repeat;#}
{#            background-size: cover;#}
{#        }#}
        body{
            background-color: darkslategrey;
        }
    </style>
</head>
   <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 offset-sm-3 pt-5 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                  <div class="text-center">
                                      <h3>Account Login</h3><hr>
                                  </div>
                                    {% for field in form %}
                                      <div class="form-group">
                                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                        {% for error in field.errors %}
                                          <span class="help-block" style="color: darkred">{{ error }}</span>
                                        {% endfor %}
                                      </div>
                                    {% endfor %}
                                    <div class="form-group text-center">
                                      <button type="submit" class="btn btn-primary">
                                          sign-in with credentials</button>
                                    </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'ecom/js/jquery.min.js' %}"></script>
        <script src="{% static 'ecom/js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'ecom/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'ecom/js/bootstrap.min.js' %}"></script>
   </body>
</html>

ecom/templates/ecom/navigation.html
      <nav class="navbar navbar-expand-md bg-light navbar-light fixed-top pt-3">
          <div class="container">
              <a class="navbar-brand" href="{% url 'index' %}"><b>FavStoreCollection</b></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navTarg">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-center" id="navTarg">
                  <ul class="navbar-nav text-white-50">
                      <li class="nav-item"><a class="nav-link active" href="{% url 'index' %}">
                          <b>All Products</b></a></li>
                      <li><a class="nav-link" href="#"><b>About us</b></a></li>
                      <li><a class="nav-link" href="#"><b>Contact us</b></a></li>
                      <li><a class="nav-link" href="{% url 'cart-summary' %}">
                          <b>Cart-Summary</b><i class="fas fa-shopping-cart fa-1x" style="color: darkslategray;"></i>
                          <span class="badge badge-dark">{{ Order_Summary.items.all.count }}</span></a></li>

                      <!---a shopping cart symbol in here-->
                      <li><a class="nav-link" href="#"><b>check-out</b></a></li>
                  </ul>
              </div>
          </div>
      </nav>